### ISSUE TITLE
Cannot open select image dialog for change pfp on Gecko

### ISSUE THREAD

**Issue by CrazyPython** [mikotoIO/mikoto#39]
**Describe the bug**
Cannot open select image dialog for change pfp on Gecko

**To Reproduce**
1. Open Mikoto in Firefox
2. Click user settings
3. Click on image profile picture

**Expected behavior**
An OS upload file dialog shows

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 112.0.2

**Comment by TheCactusBlue** [comment]
Had to do with a problem with `react-dropzone`'s `open()` call being blocked, plus misconfiguration of the GCS bucket. it has been fixed now.
