### ISSUE TITLE
[MIK-30] Fix "Open in new tab"

### ISSUE THREAD

**Issue by CrazyPython** [mikotoIO/mikoto#63]
* [ ] Opening other channels
* [ ] Opening subchannels in the same guild
* [ ] Opening channels across guilds

<sub>From [SyncLinear.com](https://synclinear.com) | [MIK-30](https://linear.app/mikoto/issue/MIK-30/fix-open-in-new-tab)</sub>

**Comment by TheCactusBlue** [comment]
FYI, Ctrl + Left click works to open in new tab. The API should be unified for both.
