### ISSUE TITLE
[MIK-33] Typing indicator

### ISSUE THREAD

**Issue by CrazyPython** [mikotoIO/mikoto#67]
With both typing_start and typing_end events

<sub>From [SyncLinear.com](https://synclinear.com) | [MIK-33](https://linear.app/mikoto/issue/MIK-33/typing-indicator)</sub>

**Comment by TheCactusBlue** [comment]
Blocked… because the user payload is too heavy and the current Recoil-based cache is difficult to wrangle into correct usage patterns. Biting the bullet and migrating entity caching to Redux Toolkit.
