### ISSUE TITLE
[MIK-29] Creating a new space should focus on the space's general, or add it to the tab list and focus it

### ISSUE THREAD

**Issue by CrazyPython** [mikotoIO/mikoto#72]
<sub>From [SyncLinear.com](https://synclinear.com) | [MIK-29](https://linear.app/mikoto/issue/MIK-29/creating-a-new-space-should-focus-on-the-spaces-general-or-add-it-to)</sub>

**Comment by TheCactusBlue** [comment]
Mikoto does not have a notion of the "general yet"

**Comment by CrazyPython** [comment]
It should focus on the most recently visited channel from that space imo
