### ISSUE TITLE
[MIK-44] Set up a React Native project using Expo

### ISSUE THREAD

**Issue by TheCactusBlue** [mikotoIO/mikoto#77]
<sub>From [SyncLinear.com](https://synclinear.com) | [MIK-44](https://linear.app/mikoto/issue/MIK-44/set-up-a-react-native-project-using-expo)</sub>

**Comment by CrazyPython** [comment]
[https://reactnative.dev/docs/environment-setup](https://reactnative.dev/docs/environment-setup)
